serverUrl: https://twenty.local

image:
  repository: twentyhq/twenty
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations: {}
  labels: {}
  hosts:
    - host: twenty.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

storage:
  type: local
  local:
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
  s3:
    region: eu-west3
    bucket: my-bucket
    endpoint: ""
    externalSecretName: s3-credentials
    accessKeyIdKey: STORAGE_S3_ACCESS_KEY_ID
    secretAccessKeyKey: STORAGE_S3_SECRET_ACCESS_KEY

redis:
  enabled: false
  externalSecretName: redis-credentials
  hostKey: REDIS_HOST
  passwordKey: REDIS_PASSWORD
  urlKey: REDIS_URL

postgres:
  enabled: false
  externalSecretName: postgres-credentials
  hostKey: POSTGRES_HOST
  userKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD
  databaseKey: POSTGRES_DB
  urlKey: DATABASE_URL

extraEnv: []
