apiVersion: v2
name: twenty
version: 0.1.0
description: Production-ready Helm chart for Twenty CRM
maintainers:
  - name: Cloud Exit
    email: contact@cloud-exit.com
type: application

dependencies:
  - name: valkey
    version: "1.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.dependencyEnabled

  - name: postgresql
    version: "15.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgres.dependencyEnabled