name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  lint-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Chart Version
        id: chart_version
        run: |
          VERSION=$(yq e '.version' Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Lint Helm chart
        run: |
          helm lint .

      - name: Package Helm chart
        run: |
          helm package . --destination .cr-release-packages

      - name: Upload packaged chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-package
          path: .cr-release-packages

      - name: Install oras CLI
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
          tar -xvf oras_1.1.0_linux_amd64.tar.gz oras
          sudo mv oras /usr/local/bin/

      - name: Push Helm chart to GitHub Packages using oras
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PACKAGE_NAME=$(ls .cr-release-packages/*.tgz | head -n1)
          oras login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          oras push ghcr.io/cloud-exit/charts/twenty:${{ steps.chart_version.outputs.version }} \
            --artifact-type application/vnd.cncf.helm.chart.v1 \
            $PACKAGE_NAME:application/tar+gzip

      - name: Push chart metadata to ArtifactHub using oras
        env:
          AH_PAT: ${{ secrets.ARTIFACTHUB_TOKEN }}
        run: |
          oras login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          oras push ghcr.io/cloud-exit/charts/twenty-helm:artifacthub.io \
            --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
            artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml